import { StyleSheet } from "react-native";

// Convert to a function that accepts theme
const createDtrStyles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.content || "#fff",
    },
    scrollView: {
      flex: 1,
      paddingBottom: 24,
    },
    scrollViewContent: {
      paddingBottom: 24,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      paddingHorizontal: 16,
      paddingVertical: 20,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    headerContent: {
      flex: 1,
    },
    welcomeText: {
      fontSize: 20,
      fontWeight: "700",
      color: theme.contentText || "#000",
      marginBottom: 12,
      letterSpacing: -0.5,
    },
    userSection: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    avatar: {
      width: 50,
      height: 50,
      borderRadius: 25,
    },
    userName: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.contentText || "#333",
    },
    logoSection: {
      alignItems: "center",
      gap: 6,
    },
    logoText: {
      fontSize: 11,
      fontWeight: "700",
      color: "#666",
      letterSpacing: 0.5,
    },
    dtrHeaderContainer: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 12,
    },
    dtrTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.contentText || "#000",
      letterSpacing: 0.5,
    },
    divider: {
      flex: 1,
      height: 1,
      backgroundColor: "#ddd",
      marginLeft: 4,
    },
    filterContainer: {
      paddingHorizontal: 16,
      marginBottom: 16,
    },
    filterLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.contentText || "#333",
      marginBottom: 10,
    },
    filterButtonsContainer: {
      flexDirection: "row",
      gap: 8,
    },
    filterButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 6,
      borderBottomWidth: 2,
      borderBottomColor: "transparent",
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    filterButtonActive: {
      borderBottomColor: theme.primary || "#F97316",
    },
    filterButtonText: {
      fontSize: 13,
      fontWeight: "600",
      color: "#666",
    },
    filterButtonTextActive: {
      color: theme.primary || "#F97316",
    },
    dropdownWrapper: {
      paddingHorizontal: 16,
      marginBottom: 12,
    },
    dropdown: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: "#ddd",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "#f9f9f9",
    },
    dropdownText: {
      fontSize: 14,
      color: "#999",
      fontWeight: "500",
    },
    dropdownMenu: {
      marginTop: 4,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: "#ddd",
      backgroundColor: theme.content || "#fff",
      overflow: "hidden",
    },
    dropdownItem: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    dropdownItemText: {
      fontSize: 14,
      color: theme.contentText || "#333",
      fontWeight: "500",
    },
    searchContainer: {
      flexDirection: "row",
      paddingHorizontal: 16,
      marginBottom: 16,
      gap: 10,
    },
    searchInput: {
      flex: 1,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: "#ddd",
      fontSize: 14,
      backgroundColor: "#f9f9f9",
      color: theme.contentText || "#333",
    },
    searchButton: {
      backgroundColor: theme.primary || "#F97316",
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 6,
      justifyContent: "center",
      alignItems: "center",
    },
    tableContainer: {
      marginHorizontal: 16,
      marginBottom: 0,
      borderWidth: 1,
      borderColor: "#ddd",
      borderRadius: 8,
      overflow: "hidden",
    },
    tableHeader: {
      flexDirection: "row",
      backgroundColor: theme.cardHeader || "#f5f5f5",
      borderBottomWidth: 1,
      borderBottomColor: "#ddd",
    },
    tableHeaderCell: {
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 13,
      fontWeight: "700",
      color: theme.buttonText || "#333",
      textAlign: "center",
    },
    tableRow: {
      flexDirection: "row",
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
      backgroundColor: theme.content || "#fff",
    },
    tableRowAlternate: {
      backgroundColor: "#fafafa",
    },
    tableCell: {
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 13,
      color: theme.contentText || "#333",
      textAlign: "center",
    },
    idCell: {
      flex: 0.8,
      minWidth: 50,
    },
    nameCell: {
      flex: 1.5,
      minWidth: 150,
    },
    schoolCell: {
      flex: 1,
      minWidth: 100,
    },
    userTypeCell: {
      flex: 1,
      minWidth: 100,
    },
    statusCell: {
      flex: 0.9,
      minWidth: 80,
    },
    actionsCell: {
      flex: 1,
      minWidth: 100,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 8,
    },
    actionButton: {
      padding: 6,
      justifyContent: "center",
      alignItems: "center",
    },
    infoBanner: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#EFF6FF",
      borderLeftWidth: 4,
      borderLeftColor: theme.primary || "#F97316",
      padding: 12,
      borderRadius: 8,
      gap: 8,
    },
    infoBannerText: {
      flex: 1,
      fontSize: 13,
      color: theme.primary || "#F97316",
      fontWeight: "500",
    },
    filtersWrapper: {
      gap: 16,
      paddingHorizontal: 16,
    },
    userTypeSearchCard: {
      backgroundColor: theme.content || "#FFFFFF",
      borderRadius: 12,
      padding: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      gap: 16,
    },
    userTypeSection: {
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: "#E5E7EB",
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.contentText || "#1F2937",
      marginBottom: 12,
    },
    filterChip: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: "#F3F4F6",
      borderWidth: 1,
      borderColor: "#E5E7EB",
    },
    filterChipActive: {
      backgroundColor: "#FFF7ED",
      borderColor: theme.primary || "#F97316",
    },
    filterChipText: {
      fontSize: 13,
      color: "#6B7280",
      fontWeight: "500",
    },
    filterChipTextActive: {
      color: theme.primary || "#F97316",
      fontWeight: "600",
    },
    cardsScrollContent: {
      flexDirection: "row",
      gap: 5,
      paddingRight: 16,
    },
    cardHorizontal: {
      backgroundColor: theme.content || "#FFFFFF",
      borderRadius: 16,
      padding: 10,
      marginBottom: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      minWidth: 300,
      width: 400,
    },
    filterHeader: {
      marginBottom: 16,
      paddingHorizontal: 16,
    },
    filterTitle: {
      fontSize: 12,
      fontWeight: "600",
      color: theme.contentText || "#1F2937",
    },
  });

export default createDtrStyles;
